### ISSUE TITLE
Support for Tripple (Single or Double) Quotes Appears Missing

### ISSUE THREAD

**Issue by michael-okeefe** [fbernier/tomlrb#3]
I was expecting the following minimal examples to parse using TOML.load_file(...):

``` toml
key1 = '''value1'''
key2 = """value2"""
```

Instead, I get:

Failed to match sequence (ALL_SPACE (TABLE / TABLE_ARRAY / KEY_VALUE / COMMENT_LINE){0, } ALL_SPACE)
