### ISSUE TITLE
Problem with table nested under array-of-tables

### ISSUE THREAD

**Issue by bettse** [fbernier/tomlrb#35]
Dependabot is trying to update tomlrb to 2.0.0 in a project I work on, but this is causing test failures, and I _think_ it might be a problem in tomlrb.  The exception I get is thrown from https://github.com/fbernier/tomlrb/blob/master/lib/tomlrb/handler.rb#L204, and I spent some time going through and trying to understand the code (and possibly a solution), but I didn't make any progress.  I created a test case, based on `spec-array-of-tables-2.toml`:

```toml
[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"

  [fruit.physical]
    shape = "long"

  [[fruit.variety]]
    name = "plantain"
```

The exception thrown will be "Tomlrb::ParseError: Key physical is already used".  I couldn't find anything in the toml docs I was consulting (https://toml.io/en/v1.0.0-rc.3#array-of-tables) indicating if this is explicitly allowed or invalid.  It does work when thrown into one online parser I tried (https://toml-parser.com/), but again, not really official.

I look forward to your thoughts.
